name: Update RSS Feed HTML Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install required packages
        run: pip install feedparser

      - name: Run the Python script
        run: python news_uploader.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news_latest.html
          git commit -m "♻️ Auto update RSS feed at $(date -u)" || echo "No changes to commit"
          git push origin main
